name: Deploy Marketplace Site

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Inject Secrets
        run: |
          # The '|' is used instead of '/' because URLs contain slashes
          sed -i "s|REPLACE_URL|${{ secrets.SUPABASEURL }}|g" script.js
          sed -i "s|REPLACE_KEY|${{ secrets.SUPABASEKEY }}|g" script.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
